- name: Play backend
  hosts: app 
  become: yes
  gather_facts: yes
  tags:
  - be-pre-build
  tasks:
    - name: hello backend
      debug:
          msg: "hello backend"
    - name: Install go
      import_role:
        name: abdennour.golang
      vars:
       golang_version: "1.14"
       golang_packages:
       - github.com/gorilla/mux
       - go.mongodb.org/mongo-driver/mongo
       golang_users:
       - "{{ ansible_ssh_user }}"
      become: yes

- name: Play backend
  hosts: app 
  become: yes
  gather_facts: no
  tags:
  - be-build
  tasks:
  - name: Workspace build exists
    file: 
      path: /opt/build_dir
      state: directory
  - name: git checkout 
    git:
      repo: https://github.com/kubernetes-tn/go-to-do-app.git
      dest: /opt/build_dir/go-to-do-app
  - name: Build code
    shell: source /etc/profile;go build -o /tmp/todo
    args:
      chdir:  /opt/build_dir/go-to-do-app/server


  
  
- name: Play backend
  hosts: app 
  gather_facts: no
  tags:
  - be-deploy
  tasks: