- name: Play backend
  hosts: app 
  become: yes
  gather_facts: yes
  tags:
  - be-pre-build
  tasks:
    - name: hello backend
      debug:
          msg: "hello backend"
    - name: Install go
      import_role:
        name: abdennour.golang
      vars:
       golang_version: "1.14"
       golang_packages:
       - github.com/gorilla/mux
       - go.mongodb.org/mongo-driver/mongo
       golang_users:
       - "{{ ansible_ssh_user }}"
      become: yes

- name: Play backend
  hosts: app 
  gather_facts: no
  tags:
  - be-build
  tasks:

  
  
- name: Play backend
  hosts: app 
  gather_facts: no
  tags:
  - be-deploy
  tasks: